# Generated by Django 3.1.7 on 2021-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='add_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='all_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='delete_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='edit_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='statics',
            field=models.BooleanField(default=False),
        ),
    ]
