# Generated by Django 3.1.7 on 2021-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210326_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
